# -*- coding: utf-8 -*-
"""Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g-GTFKCPLQPXlPsq2eeADL100Qf7cSnS
"""

from google.colab import drive
drive.mount('/content/drive')

"""Importing libraries for preprocessing"""

import pandas as pd

"""Dataset source: https://github.com/mmahbub/cpgQA"""

#importing dataset
df = pd.read_csv('/content/drive/MyDrive/cpgQA-v1.0 (1).csv')
df.head()

#dataset description
df.info()

df.head()

"""Preprocessing"""

df.isnull().sum()

"""Retreival Augmented Generation"""

!pip install langchain openai faiss-cpu pandas --quiet

#creating chunks
df["chunk"] = df["TITLE"] + " " + df["CONTEXT"]
documents = df["chunk"].tolist()

#installing langchain community because embedding class in a different package
!pip install -U langchain-community --quiet

#importing openAI embedding model to store chunks
from langchain.embeddings import OpenAIEmbeddings

#embedding_model = OpenAIEmbeddings(openai_api_key="use API key")

#storing embedding in FAISS
from langchain.vectorstores import FAISS
from langchain.docstore.document import Document

docs = [Document(page_content=chunk) for chunk in documents]
vectorstore = FAISS.from_documents(docs, embedding_model)

from langchain.chat_models import ChatOpenAI
from langchain.chains import RetrievalQA

llm = ChatOpenAI(openai_api_key="use API key", temperature=0)
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=vectorstore.as_retriever(),
    return_source_documents=True
)

def ask_user_question(qa_chain):
    print("\nType 'exit' to quit if required.\n")
    while True:
        user_question = input("Your question: ")
        if user_question.strip().lower() == "exit":
            print("Exiting. See you next time!")
            break
        try:
            response = qa_chain.invoke({"query": user_question})
            print(f"\nAnswer:\n{response['result']}\n")
        except Exception as e:
            print(f"Error: {e}\n")

ask_user_question(qa_chain)

!pip install bert-score --quiet

from bert_score import score

# Sample data
predicted_answers = [
    "The dosage is 10mg twice daily.",
    "Use Drug Y for mild symptoms."
]

ground_truth_answers = [
    "Patients should take 10 milligrams two times a day.",
    "Drug Y is recommended for mild cases."
]

# Compute BERTScore
P, R, F1 = score(predicted_answers, ground_truth_answers, lang="en", verbose=True)

# Print results
for i in range(len(predicted_answers)):
    print(f"\nExample {i+1}")
    print(f"Predicted: {predicted_answers[i]}")
    print(f"Ground Truth: {ground_truth_answers[i]}")
    print(f"BERTScore F1: {F1[i]:.4f}")